global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Maui.Alerts;
global using CommunityToolkit.Maui.Core;
global using DailyPlaylist.Model;
global using System.Collections.ObjectModel;
global using System.Diagnostics;
global using MediaManager;
global using Newtonsoft.Json;
global using System.Windows.Input;
